[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
ordo = "3kcDAfBY5Q5cKJMwWKX3DRqGg3JwQ7Tntkh8faYF5yA5"

[programs.mainnet]
ordo = "EfsKVSxQxwoR9NpZfjgWuuwpbbF14BQgrh3rt4kAs181"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "/home/tskol/.config/solana/id.json"

[scripts]
CloseOrder = "yarn run ts-node ./scripts/CloseOrder.ts"
CreateOrder = "yarn run ts-node ./scripts/CreateOrder.ts"
InitializeOraclePool = "yarn run ts-node ./scripts/InitializeOraclePool.ts"
InitializeVault = "yarn run ts-node ./scripts/InitializeVault.ts"
TakeOrder = "yarn run ts-node ./scripts/TakeOrder.ts"
initializeGlobalConfig = "yarn run ts-node ./scripts/InitializeGlobalConfig.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
