[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
limo = "82qR3ftARSeXPBg9wnVrsLsAepfvimBUCPdNuiV9unhV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# wallet = "~/.config/solana/id.json"
wallet = "./.private/deployer.json"

[scripts]
CloseOrder = "yarn run ts-node ./scripts/CloseOrder.ts"
CreateOrder = "yarn run ts-node ./scripts/CreateOrder.ts"
InitializeOraclePool = "yarn run ts-node ./scripts/InitializeOraclePool.ts"
InitializeVault = "yarn run ts-node ./scripts/InitializeVault.ts"
TakeOrder = "yarn run ts-node ./scripts/TakeOrder.ts"
initializeGlobalConfig = "yarn run ts-node ./scripts/initializeGlobalConfig.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
