[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
limo = "BQvCNSSpC4Csn5Ldr7GmLvrXnjLjLJRsDhYNMpkgJskS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/liquidonrf/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
initializeGlobalConfig = "yarn run ts-node ./scripts/initializeGlobalConfig.ts"
InitializeVault = "yarn run ts-node ./scripts/InitializeVault.ts"
InitializeOraclePool = "yarn run ts-node ./scripts/InitializeOraclePool.ts"
CreateOrder = "yarn run ts-node ./scripts/CreateOrder.ts"
TakeOrder = "yarn run ts-node ./scripts/TakeOrder.ts"
CloseOrder = "yarn run ts-node ./scripts/CloseOrder.ts"
